sensor:
#    - platform: powercalc
#      entity_id: light.gaming_room_wall_lights
#      power_sensor_id: sensor.gaming_room_wall_switch_outlets_power
      #fixed:
        #power: "{{states('sensor.gaming_room_wall_switch_outlets_power')}}"
        #energy: "{{states('sensor.gaming_room_outlets_energy')}}"
#    - platform: powercalc
#      entity_id: switch.gaming_room_wall_outlets_switch
#      fixed:
#        power: 5

  - name: Guest room - Total power
    platform: group
    unique_id: 7c699742-8468-4e35-8e39-4f9cde7314c2
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.guest_room_closet_lights_power
      - sensor.guest_room_closet_outlets_power
      - sensor.guest_room_door_outlets_ceiling_lights_power
      - sensor.guest_room_door_outlets_outlet_power
      - sensor.guest_room_windows_outlets_power

template:
  - sensor:
    - name: Guest room - Thermostat Humidity
      unique_id: d60cf603-c81c-41f9-9427-74be20630f87
      unit_of_measurement: "%"
      device_class: humidity
      state: >-
        {% set cloud_humidity = states('sensor.guest_room_thermostat_cloud_humidity') | default('unknown') %}
        {% if is_number(cloud_humidity) %}
          {{ cloud_humidity | float(0) | round(1) }}
        {% else %}
          {{ state_attr('climate.guest_room_thermostat', 'current_humidity') }}
        {% endif %}
    - name: Guest room - Closet - Thermostat Humidity
      unique_id: d2ddbe5e-6a2d-47e9-abea-7f39d59979fe
      unit_of_measurement: "%"
      device_class: humidity
      state: >-
        {% set cloud_humidity = states('sensor.guest_room_closet_thermostat_cloud_humidity') | default('unknown') %}
        {% if is_number(cloud_humidity) %}
          {{ cloud_humidity | float(0) | round(1) }}
        {% else %}
          {{ state_attr('climate.guest_room_closet_thermostat', 'current_humidity') }}
        {% endif %}

#    - name: Guest room - Total power
#      unique_id: 31fdb672-8dda-4247-9f86-f6f56298228d
#      unit_of_measurement: "W"
#      device_class: power
#      state: >-
#        {{ expand('group.guest_room_power_sensors') 
#        | rejectattr('state', 'in', ['unavailable','unknown']) 
#        | map(attribute='state') 
#        | map('float') 
#        | sum
#        | float(0)
#        | round(2)
#        }}

#    - name: Guest closet - Total power
#      unique_id: 7a807158-b9d2-43ba-b3e1-54d304a6a3e2
#      unit_of_measurement: "W"
#      device_class: power
#      state: >-
#        {{ expand('group.guest_closet_power_sensors') 
#        | rejectattr('state', 'in', ['unavailable','unknown']) 
#        | map(attribute='state') 
#        | map('float') 
#        | sum
#        | float(0)
#        | round(2)
#        }}
#    - name: Data centre - Total energy
#      unique_id: 6573e81b-3335-4ada-8dac-54e697e8e0c3
#      unit_of_measurement: "kWh"
#      device_class: energy
#      state: >-
#        {{ 0
#        +  (states('sensor.data_centre_lights_energy') | float(0))
#        +  (states('sensor.data_centre_outlets_energy') | float(0))
#        }}

#zha:
#  device_config:
#    00:12:4b:00:23:70:e7:bc-1:
#      type: 'switch'

