automation:
- alias: Guest room - Lights - Wall switch based
  id: '1660893538025'
  description: ''
  use_blueprint:
    path: EdwardTFN/light_switch_toggle.yaml
    input:
      input_entity: binary_sensor.guest_room_door_outlets_ceiling_lights_input
      light_target: light.guest_room_wall_lights
- alias: Guest room - Lights - Remote control
  id: '1668696726501'
  description: ''
  use_blueprint:
    path: dustins/zha-philips-hue-v2-smart-dimmer-switch-and-remote-rwl022.yaml
    input:
      zha_device: 4dee46fc22090c07a89fc8d35d885f0c
      Power_Press:
      - service: light.toggle
        data:
          transition: 1
        target:
          entity_id: light.guest_room_wall_lights
      Up_Press:
      - device_id: 23b99823c540e6a0265e79892b351820
        domain: light
        entity_id: light.guest_room_wall_lights
        type: brightness_increase
      Down_Press:
      - device_id: 23b99823c540e6a0265e79892b351820
        domain: light
        entity_id: light.guest_room_wall_lights
        type: brightness_decrease
      Hue_Press:
      - service: light.turn_on
        data:
          effect: "{%- set effect_index = 0 %} {%- if state_attr('light.guest_room_wall_lights',
            'effect') | default(false) %}\n  {%- if state_attr('light.guest_room_wall_lights',
            'effect') in state_attr('light.guest_room_wall_lights', 'effect_list')
            %}\n    {%- set effect_index = state_attr('light.guest_room_wall_lights',
            'effect_list').index(state_attr('light.guest_room_wall_lights', 'effect'))
            + 1 %}\n    {%- if effect_index >= (state_attr('light.guest_room_wall_lights',
            'effect_list') | list | count) %}\n      {%- set effect_index = 0 %}\n
            \   {%- endif %}\n  {%- endif %}\n{%- endif %} {{ state_attr('light.guest_room_wall_lights',
            'effect_list')[effect_index] }}"
        target:
          entity_id: light.guest_room_wall_lights
- alias: Guest room - Lights - Motion based
  id: '1669503784710'
  description: ''
  use_blueprint:
    path: EdwardTFN/light_motion_illuminance_2_levels.yaml
    input:
      motion_entity: binary_sensor.guest_room_motion
      lumens_entity: sensor.guest_room_motion_illuminance
      light_target: light.guest_room_wall_lights
      no_motion_wait_to_dimming: 120
      pause_entities_off:
      - binary_sensor.guest_room_door

light:
  - platform: group
    name: "Guest room - All lights"
    unique_id: 57021482-5abd-4737-ae65-d9edc692ae5f
    entities:
      - light.guest_room_wall_lights
      - light.guest_room_closet_lights


