sensor:
  - name: Guest room - Total power
    platform: group
    unique_id: 7c699742-8468-4e35-8e39-4f9cde7314c2
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.guest_room_closet_lights_power
      - sensor.guest_room_closet_outlets_power
      - sensor.guest_room_door_outlets_ceiling_lights_power
      - sensor.guest_room_door_outlets_outlet_power
      - sensor.guest_room_windows_outlets_power

  - name: Guest room - Total energy
    platform: integration
    unique_id: d023fdfc-7999-42a4-a2e5-c00c281e4740
    source: sensor.guest_room_total_power
    round: 2
    unit_prefix: k
    unit_time: h
    method: trapezoidal
