automation:
- alias: Guest room - Climate - Windows based
  id: '1671275057270'
  description: ''
  use_blueprint:
    path: EdwardTFN/tado_windows.yaml
    input:
      window_entity:
      - binary_sensor.guest_room_windows
      climate_target:
      - climate.guest_room_thermostat

template:
  - sensor:
    - name: Guest room - Thermostat Humidity
      unique_id: d60cf603-c81c-41f9-9427-74be20630f87
      unit_of_measurement: "%"
      device_class: humidity
      availability: "{{ is_number('sensor.guest_room_thermostat_cloud_humidity') or state_attr('climate.guest_room_thermostat', 'current_humidity') | float(-1) >= 0}}"
      state: >-
        {% if is_number('sensor.guest_room_thermostat_cloud_humidity') %}
          {{ states('sensor.guest_room_thermostat_cloud_humidity') | float(0) | round(0) }}
        {% else %}
          {{ state_attr('climate.guest_room_thermostat', 'current_humidity') | float(0) | round(0) }}
        {% endif %}
