automation:
- alias: Guest room - Climate - Windows based
  id: '1671275057270'
  description: ''
  use_blueprint:
    path: EdwardTFN/tado_windows.yaml
    input:
      window_entity:
      - binary_sensor.guest_room_windows
      climate_target:
      - climate.guest_room_thermostat
- alias: Guest room - Lights - Wall switch based
  id: '1660893538025'
  description: ''
  use_blueprint:
    path: EdwardTFN/light_switch_toggle.yaml
    input:
      input_entity: binary_sensor.guest_room_door_outlets_ceiling_lights_input
      light_target: light.guest_room_wall_lights
- alias: Guest room - Button
  id: '1661246578282'
  description: ''
  trigger:
  - device_id: a07f3f784bcb1a27fc73455441aa7b8e
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
    id: Click
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.guest_room_wall_lights
  mode: single
- alias: Guest room - Closet - Light - Door based
  id: '1661762547832'
  description: ''
  use_blueprint:
    path: EdwardTFN/set_entities_based_on_other_entities.yaml
    input:
      input_entities:
      - binary_sensor.guest_room_closet_door
      target_entities:
      - light.guest_room_closet_lights
- alias: Guest room - Covers - Shutter - Remote control
  id: '1664956189168'
  description: ''
  use_blueprint:
    path: EdwardTFN/cover_remote.yaml
    input:
      remote_device: f924ed9d99a9600cb8c516a76d023253
      cover_entity: cover.guest_room_shutter_cover
- alias: Guest room - Lights - Remote control
  id: '1668696726501'
  description: ''
  use_blueprint:
    path: dustins/zha-philips-hue-v2-smart-dimmer-switch-and-remote-rwl022.yaml
    input:
      zha_device: 4dee46fc22090c07a89fc8d35d885f0c
      Power_Press:
      - service: light.toggle
        data:
          transition: 1
        target:
          entity_id: light.guest_room_wall_lights
      Up_Press:
      - device_id: 23b99823c540e6a0265e79892b351820
        domain: light
        entity_id: light.guest_room_wall_lights
        type: brightness_increase
      Down_Press:
      - device_id: 23b99823c540e6a0265e79892b351820
        domain: light
        entity_id: light.guest_room_wall_lights
        type: brightness_decrease
      Hue_Press:
      - service: light.turn_on
        data:
          effect: "{%- set effect_index = 0 %} {%- if state_attr('light.guest_room_wall_lights',
            'effect') | default(false) %}\n  {%- if state_attr('light.guest_room_wall_lights',
            'effect') in state_attr('light.guest_room_wall_lights', 'effect_list')
            %}\n    {%- set effect_index = state_attr('light.guest_room_wall_lights',
            'effect_list').index(state_attr('light.guest_room_wall_lights', 'effect'))
            + 1 %}\n    {%- if effect_index >= (state_attr('light.guest_room_wall_lights',
            'effect_list') | list | count) %}\n      {%- set effect_index = 0 %}\n
            \   {%- endif %}\n  {%- endif %}\n{%- endif %} {{ state_attr('light.guest_room_wall_lights',
            'effect_list')[effect_index] }}"
        target:
          entity_id: light.guest_room_wall_lights
- alias: Guest room - Lights - Motion based
  id: '1669503784710'
  description: ''
  use_blueprint:
    path: EdwardTFN/light_motion_illuminance_2_levels.yaml
    input:
      motion_entity: binary_sensor.guest_room_motion
      lumens_entity: sensor.guest_room_motion_light_level
      light_target: light.guest_room_wall_lights
      no_motion_wait_to_dimming: 120
      pause_entities_off:
      - binary_sensor.guest_room_door

sensor:
  - name: Guest room - Total power
    platform: group
    unique_id: 7c699742-8468-4e35-8e39-4f9cde7314c2
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.guest_room_closet_lights_power
      - sensor.guest_room_closet_outlets_power
      - sensor.guest_room_door_outlets_ceiling_lights_power
      - sensor.guest_room_door_outlets_outlet_power
      - sensor.guest_room_windows_outlets_power

template:
  - sensor:
    - name: Guest room - Thermostat Humidity
      unique_id: d60cf603-c81c-41f9-9427-74be20630f87
      unit_of_measurement: "%"
      device_class: humidity
      state: >-
        {% set cloud_humidity = states('sensor.guest_room_thermostat_cloud_humidity') | default('unknown') %}
        {% if is_number(cloud_humidity) %}
          {{ cloud_humidity | float(0) | round(1) }}
        {% else %}
          {{ state_attr('climate.guest_room_thermostat', 'current_humidity') }}
        {% endif %}
    - name: Guest room - Closet - Thermostat Humidity
      unique_id: d2ddbe5e-6a2d-47e9-abea-7f39d59979fe
      unit_of_measurement: "%"
      device_class: humidity
      state: >-
        {% set cloud_humidity = states('sensor.guest_room_closet_thermostat_cloud_humidity') | default('unknown') %}
        {% if is_number(cloud_humidity) %}
          {{ cloud_humidity | float(0) | round(1) }}
        {% else %}
          {{ state_attr('climate.guest_room_closet_thermostat', 'current_humidity') }}
        {% endif %}
