sensor:
  - name: Guest room - Total power
    platform: group
    unique_id: 7c699742-8468-4e35-8e39-4f9cde7314c2
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.guest_room_closet_lights_power
      - sensor.guest_room_closet_outlets_power
      - sensor.guest_room_door_outlets_ceiling_lights_power
      - sensor.guest_room_door_outlets_outlet_power
      - sensor.guest_room_windows_outlets_power

template:
  - sensor:
    - name: Guest room - Thermostat Humidity
      unique_id: d60cf603-c81c-41f9-9427-74be20630f87
      unit_of_measurement: "%"
      device_class: humidity
      state: >-
        {% set cloud_humidity = states('sensor.guest_room_thermostat_cloud_humidity') | default('unknown') %}
        {% if is_number(cloud_humidity) %}
          {{ cloud_humidity | float(0) | round(1) }}
        {% else %}
          {{ state_attr('climate.guest_room_thermostat', 'current_humidity') }}
        {% endif %}
    - name: Guest room - Closet - Thermostat Humidity
      unique_id: d2ddbe5e-6a2d-47e9-abea-7f39d59979fe
      unit_of_measurement: "%"
      device_class: humidity
      state: >-
        {% set cloud_humidity = states('sensor.guest_room_closet_thermostat_cloud_humidity') | default('unknown') %}
        {% if is_number(cloud_humidity) %}
          {{ cloud_humidity | float(0) | round(1) }}
        {% else %}
          {{ state_attr('climate.guest_room_closet_thermostat', 'current_humidity') }}
        {% endif %}
