automation: !include automations.yaml

binary_sensor:
  #- platform: ping # https://www.home-assistant.io/integrations/ping/#binary-sensor
    #host: !secret ip_pc_1
    #name: "Living room - PC-1"
    #count: 2
    #scan_interval: 30

  - platform: workday # https://www.home-assistant.io/integrations/workday/
    country: SE

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

device_tracker:
  #- platform: bluetooth_tracker
    #track_new_devices: false
  #- platform: bluetooth_le_tracker
    #track_new_devices: false
  - platform: ping # https://www.home-assistant.io/integrations/ping/#presence-detection
    hosts:
      #carols_phone_ping: !secret ip_carols_phone
      #edwards_phone_ping: !secret ip_edwards_phone
      pc_1_ping: !secret ip_pc_1

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/card-mod.js


group: !include groups.yaml

homeassistant:
  packages: !include_dir_named packages

#home_connect_alt: #https://github.com/ekutner/home-connect-hass
  #client_id: !secret home_connect_alt_client_id
  #client_secret: !secret home_connect_alt_client_secret

http:
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy_1
    - !secret trusted_proxy_2

#logger:
#  default: warning
#  logs:
#    homeassistant.components.bluetooth: debug

notify: !include notifications.yaml

scene: !include scenes.yaml

shell_command: !include shell.yaml

# Text to speech
tts:
  - platform: google_translate

zha:
  enable_quirks: true
  custom_quirks_path: /config/zha/quirks

  zigpy_config: # https://github.com/zigpy/zigpy/wiki/OTA-Device-Firmware-Updates
    ota:
      otau_directory: /config/zha/zigpy_ota
      ikea_provider: true
      inovelli_provider: true
      ledvance_provider: true
      salus_provider: true
      sonoff_provider: true
      thirdreality_provider: true


zone: !include zone.yaml