automation:
- alias: Kitchen - Cooktop - Align status on 3-phases
  id: '1663411091899'
  description: ''
  use_blueprint:
    path: EdwardTFN/set_entities_based_on_other_entities.yaml
    input:
      input_entities:
      - switch.kitchen_cooktop_l1_outlet
      - switch.kitchen_cooktop_l2_outlet
      - switch.kitchen_cooktop_l3_outlet
      - switch.kitchen_cooker_hood
      target_entities:
      - switch.kitchen_cooktop_l1_outlet
      - switch.kitchen_cooktop_l2_outlet
      - switch.kitchen_cooktop_l3_outlet
      - switch.kitchen_cooker_hood
- alias: Kitchen - Cooktop - Alarms
  id: '1656410575930'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.kitchen_cooktop_l1_overheating
    - binary_sensor.kitchen_cooktop_l1_overpowering
    - binary_sensor.kitchen_cooktop_l1_overvoltage
    - binary_sensor.shellyplus1pm_7c87ce64c7b4_switch_0_overheating
    - binary_sensor.shellyplus1pm_7c87ce64c7b4_switch_0_overpowering
    - binary_sensor.shellyplus1pm_7c87ce64c7b4_switch_0_overvoltage
    - binary_sensor.shellyplus1pm_3c610579dfa8_switch_0_overheating
    - binary_sensor.shellyplus1pm_3c610579dfa8_switch_0_overpowering
    - binary_sensor.shellyplus1pm_3c610579dfa8_switch_0_overvoltage
    not_from: unavailable
    not_to: unavailable
  - platform: numeric_state
    entity_id: sensor.kitchen_cooktop_l1_device_temperature
    above: '100'
  - platform: numeric_state
    entity_id: sensor.kitchen_cooktop_l2_device_temperature
    above: '100'
  - platform: numeric_state
    entity_id: sensor.kitchen_cooktop_l3_device_temperature
    above: '100'
  condition: []
  action:
  - service: notify.signal_edward
    data:
      message: 'There is an alert in the Cooktop.

        {{ state_attr(trigger.entity_id, "friendly_name") }} is {{ states(trigger.entity_id)
        }}.'
  mode: single

sensor:
  - name: Kitchen - Cooktop - Total power
    platform: group
    unique_id: c9eaa92a-a69d-4873-8661-5dedc6d2f313
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.kitchen_cooktop_l1_outlet_power
      - sensor.kitchen_cooktop_l2_outlet_power
      - sensor.kitchen_cooktop_l3_outlet_power
