alert:
  kitchen_freezer_temperature:
    name: Kitchen - Freezer - Temperature alert
    message: >-
      The temperature in the freezer is outside the normal range ({{ states('sensor.kitchen_freezer_hygrometer_temperature') }}ºC).
      
      Please check the door and power supply.
    done_message: The temperature in the freezer is back to normal ({{ states('sensor.kitchen_freezer_hygrometer_temperature') }}ºC).
    entity_id: binary_sensor.kitchen_freezer_temperature_normal_range
    state: 'off'
    repeat: 150
    can_acknowledge: true
    skip_first: true
    notifiers:
      - signal_group_artillerigatan
  #kitchen_fridge_temperature:
    #name: Kitchen - Fridge - Temperature alert
    #message: >-
      #The temperature in the fridge is outside the normal range ({{ states('sensor.kitchen_fridge_hygrometer_temperature') }}ºC).
      #
      #Please check the door and power supply.
    #done_message: The temperature in the fridge is back to normal ({{ states('sensor.kitchen_fridge_hygrometer_temperature') }}ºC).
    #entity_id: binary_sensor.kitchen_fridge_temperature_normal_range
    #state: 'off'
    #repeat: 15
    #can_acknowledge: true
    #skip_first: true
    #notifiers:
      #- signal_group_artillerigatan

#home_connect:
#client_id: !secret home_connect_client_id
#client_secret: !secret home_connect_client_secret

sensor:
  - name: Kitchen - Table - Motion ratio in the last 10m
    platform: history_stats
    entity_id: binary_sensor.kitchen_motion_all
    state: "on"
    type: ratio
    start: "{{ (now() + timedelta(minutes=-10)) }}"
    end: "{{ now() }}"

  - name: Kitchen - Total power
    platform: group
    unique_id: ed9f9dd1-8dfc-421b-8a45-f2461ef0b468
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.kitchen_bench_left_light_power
      - sensor.kitchen_bench_outlets_1_outlets_power
      - sensor.kitchen_bench_outlets_1_usb_power
      - sensor.kitchen_bench_outlets_2_power
      - sensor.kitchen_bench_outlets_3_power
      - sensor.kitchen_bench_right_light_power
      - sensor.kitchen_ceiling_lights_table_lights_power
      - sensor.kitchen_ceiling_lights_windows_lights_power
      - sensor.kitchen_cooktop_l1_outlet_power
      - sensor.kitchen_cooktop_l2_outlet_power
      - sensor.kitchen_cooktop_l3_outlet_power
      - sensor.kitchen_dishwasher_outlet_power
      - sensor.kitchen_microwave_power
      - sensor.kitchen_oven_power
      - sensor.kitchen_refrigeration_freezer_outlet_power
      - sensor.kitchen_refrigeration_fridge_outlet_power
      - sensor.kitchen_windows_wall_outlet_power

  - name: Kitchen - Bench - Total power
    platform: group
    unique_id: 1b0da3e6-ade5-484e-bd3a-0c6ef60739ec
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.kitchen_bench_outlets_1_outlets_power
      - sensor.kitchen_bench_outlets_1_usb_power
      - sensor.kitchen_bench_outlets_2_power
      - sensor.kitchen_bench_outlets_3_power
      - sensor.kitchen_bench_left_light_power
      - sensor.kitchen_bench_right_light_power
      - sensor.kitchen_cooker_hood_power

  - name: Kitchen - Cooktop - Total power
    platform: group
    unique_id: c9eaa92a-a69d-4873-8661-5dedc6d2f313
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.kitchen_cooktop_l1_outlet_power
      - sensor.kitchen_cooktop_l2_outlet_power
      - sensor.kitchen_cooktop_l3_outlet_power

template:
  - sensor:
    - name: Kitchen - Thermostat Humidity
      unique_id: b5577dd5-bd1b-48b4-a3cc-cd20bda7d033
      unit_of_measurement: "%"
      device_class: humidity
      state: >-
        {% set cloud_humidity = states('sensor.kitchen_thermostat_cloud_humidity') | default('unknown') %}
        {% if is_number(cloud_humidity) %}
          {{ cloud_humidity | float(0) | round(1) }}
        {% else %}
          {{ state_attr('climate.kitchen_thermostat', 'current_humidity') }}
        {% endif %}

  - trigger:
    - id: Door
      platform: state
      entity_id:
        - binary_sensor.kitchen_dishwasher_door
      from:
        - "off"
        - "on"
      to:
        - "off"
        - "on"
    - id: Cycle
      platform: state
      entity_id:
        - sensor.kitchen_dishwasher_operation_state
      to:
        - "Run"
    binary_sensor:
      - name: Kitchen - Dishwasher - Door oppened after run
        unique_id: 39cd3a86-5db0-40a0-978d-29751413fc59
        state: "{{ trigger.id == 'Door' }}"
        attributes:
          triggered_by: "{{ trigger.entity_id }}"
          last_triggered: "{{ now() }}"
          trigger: "{{ trigger }}"
          door: "{{ states('binary_sensor.kitchen_dishwasher_door') }}"
          operation_state: "{{ states('sensor.kitchen_dishwasher_operation_state') }}"

