automation:
  - alias: Kitchen - Bench - Lights - Motion
    id: '1642333235058'
    description: ''
    use_blueprint:
      path: EdwardTFN/light_motion_illuminance_2_levels.yaml
      input:
        max_lumens: 15
        no_motion_wait_to_dimming: 120
        light_level_high: 100
        light_level_dimmer: 35
        motion_entity: binary_sensor.kitchen_bench_motion_occupancy
        lumens_entity: sensor.kitchen_bench_motion_light_level
        light_target: light.kitchen_bench_lights
        no_motion_wait_to_off: 15
        pause_entities_on:
        - input_boolean.home_party_mode

sensor:
  - name: Kitchen - Bench - Total power
    platform: group
    unique_id: 1b0da3e6-ade5-484e-bd3a-0c6ef60739ec
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.kitchen_bench_outlets_1_outlets_power
      - sensor.kitchen_bench_outlets_1_usb_power
      - sensor.kitchen_bench_outlets_2_power
      - sensor.kitchen_bench_outlets_3_power
      - sensor.kitchen_bench_left_light_power
      - sensor.kitchen_bench_right_light_power
      - sensor.kitchen_cooker_hood_power
