automation:
- alias: Kitchen - Always on
  id: f711c2a0-4b8a-4aed-b8bb-5a2ce62aed4f
  description: ''
  use_blueprint:
    path: EdwardTFN/always_on.yaml
    input:
      timeout: 60
      entities_list:
      - switch.kitchen_cooker_hood

sensor:
  - name: Kitchen - Total power
    platform: group
    unique_id: ed9f9dd1-8dfc-421b-8a45-f2461ef0b468
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.kitchen_bench_left_light_power
      - sensor.kitchen_bench_outlets_1_outlets_power
      - sensor.kitchen_bench_outlets_1_usb_power
      - sensor.kitchen_bench_outlets_2_power
      - sensor.kitchen_bench_outlets_3_power
      - sensor.kitchen_bench_right_light_power
      - sensor.kitchen_ceiling_lights_table_lights_power
      - sensor.kitchen_ceiling_lights_windows_lights_power
      - sensor.kitchen_cooktop_l1_outlet_power
      - sensor.kitchen_cooktop_l2_outlet_power
      - sensor.kitchen_cooktop_l3_outlet_power
      - sensor.kitchen_dishwasher_outlet_power
      - sensor.kitchen_microwave_power
      - sensor.kitchen_oven_power
      - sensor.kitchen_refrigeration_freezer_outlet_power
      - sensor.kitchen_refrigeration_fridge_outlet_power
      - sensor.kitchen_windows_wall_outlet_power
