sensor:
  - name: Laundry - Total power
    platform: group
    unique_id: c1adb8ac-8515-4959-909f-025c5ceb95a7
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.bathroom_towel_warmer_power
      - sensor.laundry_bench_outlets_power
      - sensor.laundry_dryer_outlet_power
      - sensor.laundry_washing_machine_power

  - name: Laundry - Total energy
    platform: integration
    unique_id: ffd01b7d-fa1c-4af4-83e7-2a7b53471bd4
    source: sensor.laundry_total_power
    round: 2
    unit_prefix: k
    unit_time: h
    method: trapezoidal
