sensor:
  - name: Living room - Total power
    platform: group
    unique_id: d456266c-cc95-4cb8-a4df-54ee4380aefb
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.living_room_lights_map_wall_power
      - sensor.living_room_lights_tv_wall_power
      - sensor.living_room_map_wall_outlets_power
      - sensor.living_room_tv_rack_outlets_power
      - sensor.living_room_windows_wall_outlets_power
