automation:
  - alias: Living room - Always on
    id: 75d18245-d852-41c3-bc38-085b93aaf518
    description: ''
    use_blueprint:
      path: EdwardTFN/always_on.yaml
      input:
        timeout: 60
        entities_list:
        - switch.living_room_network_strip_1_socket_1
        - switch.living_room_network_strip_1_socket_2
        - switch.living_room_network_strip_1_socket_3
        - switch.living_room_network_strip_1_socket_4
        - switch.living_room_network_strip_1_usb

sensor:
  - name: Living room - Total power
    platform: group
    unique_id: d456266c-cc95-4cb8-a4df-54ee4380aefb
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.living_room_lights_map_wall_power
      - sensor.living_room_lights_tv_wall_power
      - sensor.living_room_map_wall_outlets_power
      - sensor.living_room_tv_rack_outlets_power
      - sensor.living_room_windows_wall_outlets_power

  - name: Living room - Total energy
    platform: integration
    unique_id: a1681656-e948-47a7-b0de-7e674110bc5e
    source: sensor.living_room_total_power
    round: 2
    unit_prefix: k
    unit_time: h
    method: trapezoidal
