sensor:
  - name: Corridor - Total power
    platform: group
    unique_id: 4ab7c4c8-9d8b-4e2c-a412-e3fdf7f47b2b
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.corridor_ceiling_lights_power
      - sensor.corridor_outlet_1_power

  - name: Corridor - Total energy
    platform: integration
    unique_id: d239babe-b909-4941-af0c-864df6c67a3b
    source: sensor.corridor_total_power
    round: 2
    unit_prefix: k
    unit_time: h
    method: trapezoidal
