sensor:
  - name: Corridor - Total power
    platform: group
    unique_id: 4ab7c4c8-9d8b-4e2c-a412-e3fdf7f47b2b
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.corridor_ceiling_lights_power
      - sensor.corridor_outlet_1_power
