automation:
- alias: Guest bathroom - Lights - Motion based
  id: '1644684428323'
  description: ''
  use_blueprint:
    path: EdwardTFN/light_motion_illuminance_2_levels.yaml
    input:
      lumens_entity: sensor.guest_bathroom_motion_illuminance
      light_target: light.guest_bathroom_all_lights
      light_level_high: 50
      light_level_dimmer: 25
      no_motion_wait_to_dimming: 300
      no_motion_wait_to_off: 60
      max_lumens: 15
      bathroom_door: binary_sensor.guest_bathroom_door
      motion_entity: binary_sensor.guest_bathroom_motion_dual_sensors_state
- alias: Guest bathroom - Mirror lights - Simplified
  id: '1644684579413'
  description: ''
  use_blueprint:
    path: EdwardTFN/light_motion_illuminance_2_levels.yaml
    input:
      motion_entity: binary_sensor.guest_bathroom_motion_occupancy
      lumens_entity: sensor.guest_bathroom_motion_illuminance
      max_lumens: 1
      light_level_high: 100
      light_level_dimmer: 100
      light_target: light.guest_bathroom_mirror_lights
      no_motion_wait_to_off: 20
- alias: Guest bathroom - Mirror lights - Turn on when door opens
  id: '1661417826606'
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: e9983c431c3c0265853419df7462492e
    entity_id: binary_sensor.guest_bathroom_door
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: 47652d57654a4bb75f6f08281fb040e6
    entity_id: light.guest_bathroom_mirror_lights
    domain: light
  mode: single

binary_sensor:
  - name: Guest bathroom - Occupied
    platform: bayesian # https://www.home-assistant.io/integrations/bayesian/
    unique_id: 70b01e9d-d3ee-40ff-b0c2-bcafaba12039
    device_class: occupancy
    prior: 0.01
    probability_threshold: 0.5
    observations:
      - entity_id: sensor.guest_bathroom_motion_ratio_in_the_last_10m
        platform: numeric_state
        above: 0.1
        prob_given_true: 0.7
        prob_given_false: 0.1
      - entity_id: binary_sensor.guest_bathroom_motion_occupancy
        platform: state
        to_state: on
        prob_given_true: 0.8
        prob_given_false: 0.1
      - entity_id: binary_sensor.guest_bathroom_motion_iaszone
        platform: state
        to_state: on
        prob_given_true: 0.99
        prob_given_false: 0.25
      - entity_id: sensor.guest_bathroom_mirror_outlets_power
        platform: numeric_state
        above: 10
        prob_given_true: 0.9
        prob_given_false: 0.1
      - entity_id: input_boolean.home_empty
        platform: state
        to_state: on
        prob_given_true: 0.0
        prob_given_false: 0.01
      - entity_id: input_boolean.home_travelling_mode
        platform: state
        to_state: on
        prob_given_true: 0.0
        prob_given_false: 0.01
      - entity_id: input_boolean.home_party_mode
        platform: state
        to_state: on
        prob_given_true: 0.4
        prob_given_false: 0.1


sensor:
  - platform: history_stats
    name: Guest bathroom - Motion ratio in the last 10m
    entity_id: binary_sensor.guest_bathroom_motion_occupancy
    state: "on"
    type: ratio
    #start: "{{ (now() + timedelta(minutes=-10)) }}"
    end: "{{ now() }}"
    duration:
      hours: 24

  - name: Guest bathroom - Total power
    platform: group
    unique_id: c42393bd-7efa-43d2-b747-f7b2d86bf506
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.guest_bathroom_ceiling_light_power
      - sensor.guest_bathroom_mirror_lights_power
      - sensor.guest_bathroom_mirror_outlets_power
      - sensor.guest_bathroom_towel_warmer_power


template:
  - trigger:
    - id: Door
      platform: state
      entity_id:
        - binary_sensor.guest_bathroom_door
      from:
        - "off"
        - "on"
      to:
        - "off"
        - "on"
    - id: Motion
      platform: state
      entity_id:
        - binary_sensor.guest_bathroom_motion_iaszone
      to:
        - "on"
    binary_sensor:
      - name: Guest bathroom - Motion while door is closed
        unique_id: 2a4cfac8-4ece-4855-b282-0010f459ab5e
        state: "{{ (trigger.id == 'Motion') and is_state('binary_sensor.guest_bathroom_door', 'off') }}"
        attributes:
          triggered_by: "{{ trigger.entity_id }}"
          last_triggered: "{{ now() }}"
          trigger: "{{ trigger }}"
          door: "{{ states('binary_sensor.guest_bathroom_door') }}"
          motion: "{{ states('binary_sensor.guest_bathroom_motion_iaszone') }}"

