automation:
- alias: Hall - Vacuum - Start cleaning when battery is full and the house is empty
  id: '1637709639635'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '00'
  - platform: state
    entity_id:
    - group.hosts
    for:
      hours: 0
      minutes: 10
      seconds: 0
  - platform: numeric_state
    entity_id: sensor.hall_roomba_battery_level
    above: 75
  - platform: state
    entity_id:
    - schedule.home_quite_hours
    - input_boolean.home_party_mode
    - input_boolean.home_travelling_mode
    - input_boolean.home_empty
    - input_boolean.home_no_dogs
  condition:
  - condition: numeric_state
    entity_id: sensor.hall_roomba_battery_level
    above: '75'
  - condition: state
    entity_id: input_boolean.home_party_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.home_travelling_mode
    state: 'off'
  - condition: state
    state: 'off'
    entity_id: schedule.home_quite_hours
  - condition: not
    conditions:
    - condition: state
      entity_id: vacuum.hall_roomba
      state: cleaning
    - condition: state
      entity_id: vacuum.hall_roomba
      state: error
  - condition: state
    entity_id: group.hosts
    state: not_home
  action:
  - service: vacuum.start
    data: {}
    target:
      entity_id: vacuum.hall_roomba
  - service: notify.signal_edward
    data:
      message: Starting cleaning as nobody is in the apartment.
  mode: single
- alias: Hall - Vacuum - Notify when error
  id: '1668248809147'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - vacuum.hall_roomba
    attribute: error_code
  condition:
  - condition: numeric_state
    entity_id: vacuum.hall_roomba
    attribute: error_code
    above: 0
  action:
  - service: notify.signal_group_home
    data:
      message: 'The Roomba from hall reported an error!

        {{ state_attr(''vacuum.hall_roomba'', ''error'') }} ({{state_attr(''vacuum.hall_roomba'',
        ''error_code'')}})'
  mode: single


switch:
  - platform: template
    switches:
      hall_vacuum:
        friendly_name: Hall - Vacuum
        unique_id: 2917b087-741a-440a-bae9-4aa5bcf4dd3e
        availability_template: "{{ has_value('vacuum.hall_roomba') }}"
        value_template: "{{ is_state('vacuum.hall_roomba', 'cleaning') }}"
        turn_on:
          service: vacuum.start
          target:
            entity_id: vacuum.hall_roomba
        turn_off:
          service: vacuum.stop
          target:
            entity_id: vacuum.hall_roomba
        icon_template: >-
          {% if states('vacuum.hall_roomba') in ['cleaning', 'docked', 'returning'] %}
            mdi:robot-vacuum
          {% else %}
            mdi:robot-vacuum-off
          {% endif %}