automation:
  - alias: Hall - Lights - Motion based
    id: '1642595120266'
    description: Motion-activated light with illuminance level
    use_blueprint:
      path: EdwardTFN/light_motion_illuminance_2_levels.yaml
      input:
        light_level_high: 75
        light_level_dimmer: 25
        motion_entity: binary_sensor.hall_presence
        light_target: light.hall_ceiling_light
        no_motion_wait_to_dimming: 90
        no_motion_wait_to_off: 5
        lumens_entity: sensor.kitchen_bench_motion_light_level
        max_lumens: 15

binary_sensor:
  - platform: group
    name: Hall - Presence
    device_class: presence
    entities:
      - binary_sensor.hall_presence_motion
      - binary_sensor.hall_presence_occupancy

light:
  - name: "Hall - All lights"
    platform: group
    unique_id: 7782c1bb-f612-4f4a-9fd2-010a028ea34c
    entities:
      - light.hall_ceiling_light
