automation:
- alias: Hall - Panel - Configuration
  id: '1672253749079'
  description: ''
  use_blueprint:
    path: Blackymas/nspanel_blueprint.yaml
    input:
      nspanel_name: hall_panel
      left_button_entity: light.hall_ceiling_light
      left_button_name: Lights
      right_button_entity: switch.vw_passat_electric_climatisation
      right_button_name: Car heating
      outdoortemp: sensor.home_weather_outdoor_temperature
      humidity: sensor.corridor_air_quality_humidity
      accuweather: home
      heatingsystemflame: binary_sensor.home_heating
      climate: climate.living_room_thermostat
      weather: AccuWeather
      entity01: light.home_all_lights
      button_page01_label: Page 1
      entity01_name: All lights
      entity02: input_boolean.home_empty
      entity02_name: Empty home
      entity03: input_boolean.home_party_mode
      entity03_name: Party mode
      entity04: input_boolean.home_travelling_mode
      entity04_name: Travelling
      entity05: light.balcony_string_lights
      entity06: switch.bedroom_power_strip_1_socket_4
      entity06_name: TV Samsung
      entity07: input_button.living_room_tv_sony_toggle
      entity08: input_boolean.home_alarm
      sync_value_ha: select_no
      sync_slider_ha: select_no
      button_page02_label: Page 2
      button_page03_label: Page 3
      button_page04_label: Page 4
      entity07_name: TV Sony
      entity05_name: Balcony
      entity09_name: Displays
      entity09: switch.office_workstation_outlets_displays
      entity08_name: Alarm
      delay: 100
      hotwatertemp: sensor.home_average_room_temperature 
- alias: Hall - Panel - Wake up with motion or door
  id: '1672272202160'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.hall_all_lights
    - binary_sensor.hall_motion_occupancy
    - binary_sensor.hall_front_door
    not_to:
    - unknown
    - unavailable
  condition: []
  action:
  - service: esphome.hall_panel_send_command_printf
    data:
      cmd: page home
  - if:
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.hall_motion_occupancy
        state: 'on'
      - condition: state
        entity_id: binary_sensor.hall_front_door
        state: 'on'
      - condition: state
        entity_id: light.hall_all_lights
        state: 'on'
    - condition: state
      entity_id: switch.hall_panel_sleep_modus
      state: 'on'
    then:
    - service: switch.turn_off
      data: {}
      target:
        entity_id:
        - switch.hall_panel_sleep_modus
    - if:
      - condition: state
        entity_id: sensor.hall_panel_currentpage
        state: screensaver
      then:
      - service: esphome.hall_panel_send_command_printf
        data:
          cmd: page home
    else:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.hall_panel_sleep_modus
  mode: single
