automation:
  - alias: Hall - Panel - Wake up with motion or door
    id: '1672272202160'
    description: ''
    trigger:
    - platform: state
      entity_id:
      - light.hall_all_lights
      - binary_sensor.hall_presence
      - binary_sensor.hall_front_door
      not_to:
      - unknown
      - unavailable
    condition: []
    action:
    - if:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.hall_presence
          state: 'on'
        - condition: state
          entity_id: binary_sensor.hall_front_door
          state: 'on'
        - condition: state
          entity_id: light.hall_all_lights
          state: 'on'
      - condition: state
        entity_id: sensor.hall_panel_nspanel_event
        state: '{"page": "screensaver", "component": "currentpage", "value": "pagechange"}'
      then:
        - service: esphome.hall_panel_send_command_printf
          data:
            cmd: page home
      else:
        - if:
          - condition: not
            conditions:
            - condition: state
              entity_id: binary_sensor.hall_presence
              state: 'on'
            - condition: state
              entity_id: binary_sensor.hall_front_door
              state: 'on'
            - condition: state
              entity_id: light.hall_all_lights
              state: 'on'
            - condition: state
              entity_id: sensor.hall_panel_nspanel_event
              state: '{"page": "screensaver", "component": "currentpage", "value": "pagechange"}'
          then:
            - delay: 20
            - service: esphome.hall_panel_send_command_printf
              data:
                cmd: page screensaver
    mode: restart

light:
  - platform: template
    lights:
      hall_panel_display:
        friendly_name: 'Hall - Panel - Display'
        availability_template: '{{ states("sensor.hall_panel_nspanel_event") not in ["unavailable", "unknown", "", None] }}'
        value_template: '{{ "screensaver" not in states("sensor.hall_panel_nspanel_event") }}'
        icon_template: '{{ "mdi:power-sleep" if "screensaver" in states("sensor.hall_panel_nspanel_event") else "mdi:tablet-dashboard" }}'
        level_template: '{{ (states("number.hall_panel_display_brightness") | int(0) / 100 * 255) | round(0) }}'
        turn_on:
          service: esphome.hall_panel_send_command_printf
          data:
            cmd: page home
        turn_off:
          service: esphome.hall_panel_send_command_printf
          data:
            cmd: page screensaver
        set_level:
          service: number.set_value
          data:
            value: '{{ (brightness / 255 * 100) | round(0) | int }}'
          target:
            entity_id: number.hall_panel_display_brightness
