sensor:
  - platform: statistics
    name: Home - Internet - Download average speed
    unique_id: c216bf95-fd94-488b-9c01-422b1290b150
    entity_id: sensor.speedtest_download
    state_characteristic: average_linear
    max_age:
      hours: 6
  - platform: statistics
    name: Home - Internet - Upload average speed
    unique_id: d83edcba-63d4-4251-b6b7-ef8fdf6c0c22
    entity_id: sensor.speedtest_upload
    state_characteristic: average_linear
    max_age:
      hours: 6
  - platform: statistics
    name: Home - Internet - Ping average speed
    unique_id: 587e6bf0-58de-40dc-ba40-79cd08eedfa4
    entity_id: sensor.speedtest_ping
    state_characteristic: average_linear
    max_age:
      hours: 6