automation:

- alias: Office - Workstation - Occupation based
  id: '1668783696394'
  description: ''
  trigger:
  - id: motion
    platform: state
    entity_id:
    - binary_sensor.office_workstation_motion
    to: 'on'
  condition: []
  action:
  - alias: Turn on the workstation
    if:
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.office_workstation_outlets_displays
        state: 'off'
      - condition: state
        entity_id: switch.office_workstation_outlets_docking_station
        state: 'off'
    then:
    - alias: Notification - Turning on the workstation
      service: notify.edward_s_laptop
      data:
        message: Turning on workstation...
      continue_on_error: true
    - service: switch.turn_on
      data: {}
      target:
        entity_id:
        - switch.office_workstation_outlets_displays
        - switch.office_workstation_outlets_docking_station
      continue_on_error: true
    enabled: true
    continue_on_error: true
  - alias: Wait until there is no motion from device
    wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.office_workstation_motion
      from: 'on'
      to: 'off'
  - if:
    - condition: state
      entity_id: switch.office_workstation_outlets_displays
      state: 'on'
    then:
    - alias: Wait the number of seconds that has been set
      delay: 600
  - if:
    - condition: state
      entity_id: switch.office_workstation_outlets_displays
      state: 'on'
    then:
    - alias: Notification - Turn off the displays soon
      service: notify.edward_s_laptop
      data:
        message: Workstation will turn off soon...
      continue_on_error: true
    - delay: 300
  - if:
    - condition: state
      entity_id: switch.office_workstation_outlets_displays
      state: 'on'
    then:
    - alias: Notification - Turning off the displays
      service: notify.edward_s_laptop
      data:
        message: Turning off displays...
      enabled: true
      continue_on_error: true
    - service: switch.turn_off
      target:
        entity_id: switch.office_workstation_outlets_displays
      data: {}
    - delay: 2700
  - if:
    - condition: state
      entity_id: switch.office_workstation_outlets_displays
      state: 'off'
    - condition: state
      entity_id: switch.office_workstation_outlets_docking_station
      state: 'off'
    then:
    - stop: Devices already off
  - alias: Notification - Turning off docking station
    service: notify.edward_s_laptop
    data:
      message: Turning off docking station...
    enabled: true
    continue_on_error: true
  - delay: 5
  - service: homeassistant.turn_off
    target:
      entity_id:
      - switch.office_workstation_outlets_displays
      - switch.office_workstation_outlets_docking_station
      - light.office_workstation_lights
    data: {}
  - service: button.press
    data: {}
    target:
      entity_id: button.mobile_edwards_laptop_sleep
  mode: restart
- alias: Office - Lights - Motion based
  id: '1669505865097'
  use_blueprint:
    path: EdwardTFN/light_motion_illuminance_2_levels.yaml
    input:
      motion_entity: binary_sensor.office_motion_all
      lumens_entity: sensor.office_motion_light_level
      light_target: light.office_ceiling_lines
      no_motion_wait_to_dimming: 90
      pause_entities_off:
      - binary_sensor.office_door
      light_level_high: 65
      light_level_dimmer: 30
      max_lumens: 30
      occupancy_ratio_entity: []
- alias: Office - Workstation - Cube
  id: '1643883389793'
  description: ''
  use_blueprint:
    path: EdwardTFN/zha_aqara_cube_simple.yaml
    input:
      last_face_input: input_number.office_cube_last_activated_face
      cube: cee0a393afbe9b83b66284988780d061
      face_1_knock:
      - service: light.toggle
        data:
          transition: 1
          brightness_pct: 50
          color_temp: 230
        target:
          entity_id: light.office_workstation_lights
      face_1_rotate_counter_clockwise:
      - device_id: 5a5dd33d7bd421bc2afe0bb014d92337
        domain: light
        entity_id: light.office_workstation_lights_left
        type: brightness_decrease
      - device_id: 6edbdadfce89c79507b7272c7c977037
        domain: light
        entity_id: light.office_workstation_lights_right
        type: brightness_decrease
      face_1_rotate_clockwise:
      - device_id: 5a5dd33d7bd421bc2afe0bb014d92337
        domain: light
        entity_id: light.office_workstation_lights_left
        type: brightness_increase
      - device_id: 6edbdadfce89c79507b7272c7c977037
        domain: light
        entity_id: light.office_workstation_lights_right
        type: brightness_increase
      face_4_knock:
      - service: light.toggle
        data:
          transition: 1
          brightness_pct: 50
        target:
          entity_id: light.office_ceiling_lines
      face_2_knock:
      - choose:
        - conditions:
          - condition: or
            conditions:
            - condition: device
              device_id: 2e935ff845c97cb19fc36d05e1d50415
              domain: cover
              entity_id: cover.office_roller_blind_cover
              type: is_opening
            - condition: device
              device_id: 2e935ff845c97cb19fc36d05e1d50415
              domain: cover
              entity_id: cover.office_roller_blind_cover
              type: is_closing
          sequence:
          - service: cover.stop_cover
            data: {}
            target:
              device_id: 2e935ff845c97cb19fc36d05e1d50415
        - conditions:
          - condition: device
            device_id: 2e935ff845c97cb19fc36d05e1d50415
            domain: cover
            entity_id: cover.office_roller_blind_cover
            type: is_open
          sequence:
          - service: cover.close_cover
            data: {}
            target:
              device_id: 2e935ff845c97cb19fc36d05e1d50415
        - conditions:
          - condition: device
            device_id: 2e935ff845c97cb19fc36d05e1d50415
            domain: cover
            entity_id: cover.office_roller_blind_cover
            type: is_closed
          sequence:
          - service: cover.open_cover
            data: {}
            target:
              device_id: 2e935ff845c97cb19fc36d05e1d50415
        default: []
      face_3_knock:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.office_workstation_outlets_docking_station
      face_3_counter_clockwise:
      - choose:
        - conditions:
          - condition: not
            conditions:
            - condition: device
              device_id: 216297d2524fa8459f265e6a9930f739
              domain: vacuum
              entity_id: vacuum.hall_roomba
              type: is_docked
            - condition: device
              device_id: 216297d2524fa8459f265e6a9930f739
              domain: vacuum
              entity_id: vacuum.hall_roomba
              type: is_cleaning
          sequence:
          - device_id: 216297d2524fa8459f265e6a9930f739
            domain: vacuum
            entity_id: vacuum.hall_roomba
            type: dock
        default: []
      face_3_rotate_counter_clockwise: []
      face_2_rotate_clockwise: []
      face_5_knock:
      - service: switch.toggle
        data: {}
        target:
          entity_id:
          - switch.office_workstation_outlets_displays
      face_4_rotate_counter_clockwise:
      - device_id: 23b99823c540e6a0265e79892b351820
        domain: light
        entity_id: light.office_ceiling_lines
        type: brightness_decrease
      face_4_rotate_clockwise:
      - device_id: 23b99823c540e6a0265e79892b351820
        domain: light
        entity_id: light.office_ceiling_lines
        type: brightness_increase
      face_2_rotate_counter_clockwise: []
      face_5_rotate_counter_clockwise: []
- alias: Office - Covers - Remote controlled (door)
  id: '1661507182774'
  description: ''
  use_blueprint:
    path: EdwardTFN/cover_remote.yaml
    input:
      remote_device: 5acfbea46187a1d3c06c2dca49bd717b
      cover_entity: cover.office_shutters_all
- alias: Office - Covers - Remote controlled 2
  id: '1661507207658'
  description: ''
  use_blueprint:
    path: EdwardTFN/cover_remote.yaml
    input:
      remote_device: d420aff39bfba16f659c207dc05e2743
      cover_entity: cover.office_shutters_all
- alias: Office - Covers - Sunset/sunrise based
  id: '1662154991151'
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - sensor.civil_solar_day_status
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
  - condition: state
    entity_id: binary_sensor.office_door
    state: 'on'
  action:
  - if:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
    then:
    - service: cover.open_cover
      data: {}
      target:
        entity_id:
        - cover.office_roller_blinds_all
        - cover.office_shutters_all
    else:
    - service: cover.set_cover_position
      data:
        position: 40
      target:
        entity_id: cover.office_roller_blind_1_cover
    - service: cover.close_cover
      data: {}
      target:
        entity_id: cover.office_roller_blind_2_cover
  mode: restart
- alias: Office - Covers - Bunkebergsgatan - Weather based
  id: '1663594463162'
  description: ''
  use_blueprint:
    path: EdwardTFN/cover_weather.yaml
    input:
      cover_list:
      - cover.office_shutter_1_cover
      weather_entity: weather.home
      windows_azimuth: '255'
- alias: Office - Covers - School - Weather based
  id: '1663594596961'
  description: ''
  use_blueprint:
    path: EdwardTFN/cover_weather.yaml
    input:
      cover_list:
      - cover.office_shutter_2_cover
      weather_entity: weather.home
      windows_azimuth: '345'
- alias: Office - Lights - Wall switch based
  id: '1660893344529'
  description: ''
  use_blueprint:
    path: EdwardTFN/light_switch_toggle.yaml
    input:
      input_entity: binary_sensor.office_windows_outlets_ceiling_lights_input
      light_target: light.office_ceiling_lines
- alias: Office - Workstation - Lights - Laptop's camera based
  id: '1662056357187'
  description: ''
  use_blueprint:
    path: EdwardTFN/set_entities_based_on_other_entities.yaml
    input:
      input_entities:
      - binary_sensor.mobile_edwards_laptop_webcamactive
      target_entities:
      - light.office_workstation_lights
      pause_entities:
      - input_boolean.home_travelling_mode
- alias: Office - Workstation - Turn on USB power when NFC tag is scanned
  id: '1664282492813'
  description: ''
  trigger:
  - platform: tag
    tag_id: c7b58905-b6b1-4fb5-b9dd-622054bf3df5
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.office_workstation_power_strip_usb
  mode: single
- alias: Office - Roller blind 1 - Remote controlled
  id: '1661506655442'
  description: ''
  use_blueprint:
    path: EdwardTFN/cover_remote.yaml
    input:
      remote_device: 655699530e3a218357784fa5b32838d2
      cover_entity: cover.office_roller_blinds_all

sensor:
  - platform: history_stats
    name: Office - Workstation - Motion ratio in the last 10m
    entity_id: binary_sensor.office_workstation_motion
    state: "on"
    type: ratio
    #start: "{{ (now() + timedelta(minutes=-10)) }}"
    end: "{{ now() }}"
    duration:
      minutes: 10