automation:
  - alias: Office - Lights - Motion based
    id: '1669505865097'
    use_blueprint:
      path: EdwardTFN/light_motion_illuminance_2_levels.yaml
      input:
        motion_entity: binary_sensor.office_motion
        lumens_entity: sensor.office_motion_illuminance
        light_target: light.office_ceiling_lines
        no_motion_wait_to_dimming: 60
        no_motion_wait_to_off: 30
        light_level_high: 35
        light_level_dimmer: 15
        max_lumens: 30
        occupancy_ratio_entity: []
  - alias: Office - Lights - Wall switch based
    id: '1660893344529'
    description: ''
    use_blueprint:
      path: EdwardTFN/light_switch_toggle.yaml
      input:
        input_entity: binary_sensor.office_lights_outlet_input
        light_target: light.office_ceiling_lines

light:
  - name: "Office - All lights"
    platform: group
    unique_id: 5b9b2fd0-edec-4ee9-8488-11abcd5d5b39
    entities:
      - light.office_ceiling_lines
      - light.office_workstation_lights
