binary_sensor:
  - name: Office - Presence
    platform: group
    unique_id: f4bc1d3b-a99f-47c4-95f6-99833b3d5451
    device_class: presence
    entities:
      - binary_sensor.office_motion_occupancy
      - binary_sensor.office_motion_on_off
      - binary_sensor.office_workstation_presence_motion
      - binary_sensor.office_workstation_presence_occupancy
