automation:
  - alias: Office - Climate - Windows based
    id: '1671275373606'
    description: ''
    use_blueprint:
      path: EdwardTFN/tado_windows.yaml
      input:
        window_entity:
        - binary_sensor.office_windows_1
        - binary_sensor.office_windows_2_opening
        climate_target:
        - climate.office_thermostat_1
        - climate.office_thermostat_2

#climate:
#  - platform: climate_group # https://github.com/daenny/climate_group
#    name: Office - Thermostat
#    temperature_unit: C
#    entities:
#      - climate.office_thermostat_1
#      - climate.office_thermostat_2

#generic_hygrostat: # https://www.home-assistant.io/integrations/generic_hygrostat/
#- name: Office - Hygrostat
##unique_id: 0e70550f-baac-4679-8179-1be50ebd94ba
#humidifier: switch.office_workstation_power_strip_switch_1
#target_sensor: sensor.office_hygrometer_humidity
#min_humidity: 0
#max_humidity: 100
#target_humidity: 30
#away_humidity: 25
#dry_tolerance: 2
#device_class: humidifier
#initial_state: true
#min_cycle_duration:
#minutes: 5

group:
  office_thermostats:
    name: Office - Thermostats
    entities:
      - climate.office_thermostat_1
      - climate.office_thermostat_2

sensor:
  - name: Office - Current temperature (mean)
    platform: group
    unique_id: f5f11226-ab8d-41eb-80cb-c0303396e45e
    type: mean
    unit_of_measurement: °C
    #icon: mdi:thermometer
    device_class: temperature
    state_class: measurement
    entities:
      - sensor.office_thermostat_1_current_temperature
      - sensor.office_thermostat_2_current_temperature
      - sensor.office_hygrometer_temperature

template:
  - sensor:
      - name: Office - Thermostat Humidity
        unique_id: 5f8f23b4-d33d-4f43-8b0b-bf4bc1ba0f55
        unit_of_measurement: "%"
        device_class: humidity
        availability: "{{ is_number(states('sensor.office_thermostat_cloud_humidity')) or state_attr('climate.office_thermostat_1', 'current_humidity') | float(-1) >= 0}}"
        state: >-
          {% if is_number(states('sensor.office_thermostat_cloud_humidity')) %}
            {{ states('sensor.office_thermostat_cloud_humidity') | float(0) | round(0) }}
          {% else %}
            {{ state_attr('climate.office_thermostat_1', 'current_humidity') | float(0) | round(0) }}
          {% endif %}
