sensor:
  - platform: history_stats
    name: Office - Workstation - Motion ratio in the last 10m
    entity_id: binary_sensor.office_workstation_motion_occupancy
    state: "on"
    type: ratio
    #start: "{{ (now() + timedelta(minutes=-10)) }}"
    end: "{{ now() }}"
    duration:
      minutes: 10