binary_sensor:
  - name: Office - Workstation - Presence
    platform: group
    unique_id: 82ac4212-9cd5-4154-8e83-0a525b6c757c
    device_class: motion
    entities:
      - binary_sensor.office_workstation_1_presence_motion
      - binary_sensor.office_workstation_1_presence_occupancy
      - binary_sensor.office_workstation_2_presence_motion
      - binary_sensor.office_workstation_2_presence_occupancy

sensor:
  - platform: history_stats
    name: Office - Workstation - Motion ratio in the last 10m
    entity_id: binary_sensor.office_workstation_presence
    state: "on"
    type: ratio
    #start: "{{ (now() + timedelta(minutes=-10)) }}"
    end: "{{ now() }}"
    duration:
      minutes: 10
