automation:
  - alias: Office - Covers - Remote controlled (door)
    id: '1661507182774'
    description: ''
    use_blueprint:
      path: EdwardTFN/cover_remote.yaml
      input:
        remote_device: 5acfbea46187a1d3c06c2dca49bd717b
        cover_entity: cover.office_shutters_all
  - alias: Office - Covers - Shutters - Sunset/sunrise based
    id: '1662154991151'
    description: ''
    trigger:
    - platform: state
      entity_id:
      - sensor.civil_solar_day_status
      for:
        minutes: 1
    - platform: state
      entity_id:
      - schedule.home_quite_hours
    condition: [ ]
    action:
    - if:
      - condition: state
        entity_id: sun.sun
        state: above_horizon
      - condition: state
        entity_id: schedule.home_quite_hours
        state: 'off'
      then:
      - service: cover.open_cover
        data: {}
        target:
          entity_id:
          - cover.office_shutters_all
      else:
      - service: cover.close_cover
        data: {}
        target:
          entity_id:
          - cover.office_shutters_all
        continue_on_error: true
      - service: cover.close_cover
        data: {}
        target:
          entity_id:
            - cover.guest_room_shutter_cover
    mode: restart
  - alias: Office - Cover - Roller blind 1
    id: '1690925441280'
    description: ''
    trigger:
    - platform: state
      entity_id:
      - weather.home
      - sun.sun
      - cover.office_shutter_1_cover
    condition: []
    action:
    - if:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 6
      - condition: or
        conditions:
        - condition: state
          entity_id: weather.home
          state: sunny
        - condition: state
          entity_id: weather.home
          state: partlycloudy
        alias: It's is sunny
      - condition: state
        entity_id: cover.office_shutter_1_cover
        state: open
      - condition: numeric_state
        entity_id: sun.sun
        attribute: azimuth
        above: 210
        below: 300
      then:
      - if:
        - condition: state
          entity_id: cover.office_roller_blind_1_cover
          state: open
        then:
        - service: cover.close_cover
          data: {}
          target:
            entity_id: cover.office_roller_blind_1_cover
      else:
      - if:
        - condition: state
          entity_id: cover.office_roller_blind_1_cover
          state: closed
        then:
        - service: cover.open_cover
          data: {}
          target:
            entity_id: cover.office_roller_blind_1_cover
    mode: single
  - alias: Office - Cover - Roller blind 2
    id: '1690925441280b'
    description: ''
    trigger:
    - platform: state
      entity_id:
      - weather.home
      - sun.sun
      - cover.office_shutter_2_cover
    condition: []
    action:
    - if:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 6
      - condition: or
        conditions:
        - condition: state
          entity_id: weather.home
          state: sunny
        - condition: state
          entity_id: weather.home
          state: partlycloudy
        alias: It's is sunny
      - condition: state
        entity_id: cover.office_shutter_2_cover
        state: open
      - condition: numeric_state
        entity_id: sun.sun
        attribute: azimuth
        above: 255
      then:
      - if:
        - condition: state
          entity_id: cover.office_roller_blind_1_cover
          state: open
        then:
        - service: cover.close_cover
          data: {}
          target:
            entity_id: cover.office_roller_blind_2_cover
      else:
      - if:
        - condition: state
          entity_id: cover.office_roller_blind_2_cover
          state: closed
        then:
        - service: cover.open_cover
          data: {}
          target:
            entity_id: cover.office_roller_blind_2_cover
    mode: single

cover:
  - name: Office - Shutters - All
    platform: group
    unique_id: 270949d7-54b3-40ad-acea-d6efdc22dc5f
    entities:
      - cover.office_shutter_1_cover
      - cover.office_shutter_2_cover

  - name: Office - Roller blinds - All
    platform: group
    unique_id: f0c6d5c9-ea29-4531-b564-87ae84ad0b9e
    entities:
      - cover.office_roller_blind_1_cover
      - cover.office_roller_blind_2_cover

