automation:
- alias: Office - Workstation - Lights - Laptop's camera based
  id: '1662056357187'
  description: ''
  use_blueprint:
    path: EdwardTFN/set_entities_based_on_other_entities.yaml
    input:
      input_entities:
      - binary_sensor.mobile_edwards_laptop_webcamactive
      target_entities:
      - light.office_workstation_lights
      pause_entities:
      - input_boolean.home_travelling_mode

light:
  - name: Office - Workstation lights
    platform: group
    unique_id: 5e8e02ac-b24c-46fc-8ecf-6ebfed97c0c1
    entities:
      - light.office_workstation_lights_left
      - light.office_workstation_lights_right
