sensor:
  - name: Office - Total power
    platform: group
    unique_id: bc1b1004-a388-4465-9a1f-8d392901a99f
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.office_door_outlets_power
      - sensor.office_windows_outlets_ceiling_lights_power
      - sensor.office_windows_outlets_outlets_power

  - name: Office - Total energy
    platform: integration
    unique_id: d3687764-e2ad-4b5e-9cbd-aa33ff7d22e1
    source: sensor.office_total_power
    round: 2
    unit_prefix: k
    unit_time: h
    method: trapezoidal

zha:
  device_config:
    70:b3:d5:2b:60:01:20:b2_1:
      type: "switch"
    70:b3:d5:2b:60:01:20:b2_2:
      type: "switch"
    70:b3:d5:2b:60:01:20:b2_3:
      type: "switch"
    70:b3:d5:2b:60:01:20:b2_4:
      type: "switch"
    70:b3:d5:2b:60:01:20:b2_5:
      type: "switch"
