esphome:
    name: ${device_name}
    friendly_name: ${friendly_name}

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

packages:
  wifi: !include config_wifi.yaml
  time: !include config_sntp.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable over-the-air updates
ota:

# Use the blue LED in the device as a status LED, which will blink if there are warnings (slow) or errors (fast)
status_led:
  pin:
    number: GPIO2
    inverted: True

binary_sensor:
  - <<: !include binary_sensor_status.yaml

button:
  - <<: !include button_restart.yaml
  - <<: !include button_restart_safe_mode.yaml
  #- <<: !include button_wifi_restart.yaml

sensor:
  - <<: !include sensor_uptime.yaml
  - <<: !include sensor_wifi.yaml
  - <<: !include sensor_wifi_signal_percentage.yaml
  #- <<: !include sensor_api_status.yaml

text_sensor:
  - <<: !include text_sensor_version.yaml
