substitutions:
  friendly_name: ${device_name}
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

packages:
  wifi: !include config_wifi.yaml
  #time: !include config_sntp.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable over-the-air updates
ota:

binary_sensor:
  #- <<: !include binary_sensor_status.yaml
  - platform: gpio
    name: "Switch"
    pin: GPIO4
    on_press:
      then:
        - switch.turn_on: "relay"
    on_release:
      then:
        - switch.turn_off: "relay"
    filters:
      - delayed_on_off: 50ms

button:
  - <<: !include button_restart.yaml
  - <<: !include button_restart_safe_mode.yaml
  #- <<: !include button_wifi_restart.yaml

output:
  - platform: gpio
    id: "relay_output"
    pin: GPIO26

sensor:
  #- <<: !include sensor_uptime.yaml
  - <<: !include sensor_wifi.yaml
  #- <<: !include sensor_wifi_signal_percentage.yaml
  #- <<: !include sensor_api_status.yaml

  - name: "Temperature"
    platform: ntc
    sensor: temp_resistance_reading
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "80.0"
        then:
          - switch.turn_off: "relay"
  - id: temp_resistance_reading
    platform: resistance
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - id: temp_analog_reading
    platform: adc
    pin: GPIO32
    attenuation: 11db

  - platform: adc
    name: "Relay Supply Voltage"
    pin: GPIO33
    attenuation: 11db
    filters:
      - multiply: 8

  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO23
      inverted: true
    cf_pin: GPIO5
    cf1_pin: GPIO18
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "Current"
      unit_of_measurement: A
      accuracy_decimals: 3
      icon: mdi:flash-outline
    voltage:
      name: "Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline
    power:
      name: "Power"
      unit_of_measurement: W
      id: power
      icon: mdi:flash-outline
      on_value_range:
        - above: "3600"
          then:
            - switch.turn_off: "relay"
    change_mode_every: 2
    update_interval: 10s

  - platform: total_daily_energy
    name: "Daily energy consumed"
    power_id: power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:clock-alert

status_led:
  pin:
    number: GPIO0
    inverted: true

switch:
  - platform: output
    id: "relay"
    name: "Relay"
    output: "relay_output"

#text_sensor:
  #- <<: !include text_sensor_version.yaml

time:
  - platform: homeassistant
