wifi:
  networks:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
  domain: !secret lan_domain
  fast_connect: true
  ap:
    ssid: "CostaFirmo ESPHome fallback"
    password: !secret fallback_password

