#sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: WiFi signal
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic
    #icon: "mdi:wifi"
    device_class: signal_strength
    state_class: measurement
