sensor:
  - name: Media centre - Total power
    platform: group
    unique_id: 6261b8f8-27d2-48dd-b924-5812ffcb983a
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.media_centre_switch_outlets_power
      - sensor.media_centre_switch_power_strip_power

  - name: Media centre - Total energy
    platform: integration
    unique_id: 7eaecc6c-1be6-4cb8-a817-2996117bf951
    source: sensor.media_centre_total_power
    round: 2
    unit_prefix: k
    unit_time: h
    method: trapezoidal
