script:
  media_centre_router_power_cycle:
    alias: Media centre - Router - Power cycle
    icon: mdi:router-wireless-off
    mode: single
    sequence:
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.media_centre_power_strip_socket_1
    - delay:
        hours: 0
        minutes: 0
        seconds: 30
        milliseconds: 0
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.media_centre_power_strip_socket_1

sensor:
  - name: Media centre - Total power
    platform: group
    unique_id: 6261b8f8-27d2-48dd-b924-5812ffcb983a
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.media_centre_switch_outlets_power
      - sensor.media_centre_switch_power_strip_power

template:
  - binary_sensor:
    - name: Media centre - Internet status
      unique_id: c48b19c3-7288-477f-94b8-1c201b6ade7a
      device_class: connectivity
      state: "{{ states('binary_sensor.aimesh_router_wan') }}"

#  - sensor:
#    - name: Media centre - Total power
#      unique_id: 06667410-fd9d-4122-914a-b81aad5d49d8
#      unit_of_measurement: "W"
#      device_class: power
#      state: >-
#        {{ expand('group.media_centre_power_sensors') 
#        | rejectattr('state', 'in', ['unavailable','unknown']) 
#        | map(attribute='state') 
#        | map('float') 
#        | sum
#        | float(0)
#        | round(2)
#        }}
