cover:
  - platform: template
    covers:
      bedroom_curtains: # https://github.com/OpenWonderLabs/SwitchBotAPI
        unique_id: 468a2dbd-ec1e-4788-8a2f-66c91a1d22ee
        device_class: curtain
        friendly_name: "Bedroom Curtains"
        position_template: "{{ states('sensor.bedroom_curtain_position') | float(0) | round(0) }}"
        open_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_deviceId
            command: "turnOn"
        close_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_deviceId
            command: "turnOff"
        stop_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_deviceId
            command: "turnOff"
        set_cover_position:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_deviceId
            command: "setPosition"
            parameter: "0,ff,{{position | float(0) | round(0)}}"

rest_command:
  switchbot_device_command:
    url: "https://api.switch-bot.com/v1.0/devices/{{ deviceId }}/commands"
    method: post
    content_type: "application/json"
    headers:
      Authorization: !secret switchbot_api
    payload: '{"command": "{{ command }}","parameter": "{{ parameter | default([]) }}"}'
  switchbot_scene_execute:
    url: "https://api.switch-bot.com/v1.0/scenes/{{ sceneId }}/execute"
    method: post
    content_type: "application/json"
    headers:
      Authorization: !secret switchbot_api

sensor:
    - name: Bedroom - Curtain - Position
      platform: rest
      resource: !secret switchbot_bedroom_status_url
      method: GET
      scan_interval: 600
      headers:
        Authorization: !secret switchbot_api
        Content-Type: "application/json"
      value_template: "{{ max(0,min(100,(100 - (value_json.body.slidePosition | float(0))))) | float(0) }}"
      json_attributes_path: "$.body"
      json_attributes:
        - deviceId
        - deviceType
        - hubDeviceId
        - calibrate
        - group
        - moving
        - slidePosition
