generic_hygrostat: # https://www.home-assistant.io/integrations/generic_hygrostat/
  - name: Office - Hygrostat
    #unique_id: 0e70550f-baac-4679-8179-1be50ebd94ba
    humidifier: switch.office_workstation_power_strip_switch_1
    target_sensor: sensor.office_thermostat_humidity
    min_humidity: 0
    max_humidity: 100
    target_humidity: 45
    away_humidity: 35
    dry_tolerance: 2
    device_class: humidifier
    initial_state: true
    min_cycle_duration:
      minutes: 5

sensor:
    - platform: history_stats
      name: Office - Workstation - Motion ratio in the last 10m
      entity_id: binary_sensor.office_workstation_motion_occupancy
      state: "on"
      type: ratio
      start: "{{ (now() + timedelta(minutes=-10)) }}"
      end: "{{ now() }}"

#    - platform: powercalc
#      entity_id: light.office_wall_lights
#      power_sensor_id: sensor.office_wall_lights_outlet_power
      #fixed:
        #power: "{{states('sensor.office_wall_lights_outlet_power')}}"
      #energy_sensor_id: sensor.office_wall_lights_outlet_energy
      #standby_power: 12.7


template:
  - sensor:
    - name: Office - Thermostat Humidity
      unique_id: 5f8f23b4-d33d-4f43-8b0b-bf4bc1ba0f55
      unit_of_measurement: "%"
      device_class: humidity
      state: >-
        {% set cloud_humidity = states('sensor.office_thermostat_cloud_humidity') | default('unknown') %}
        {% if is_number(cloud_humidity) %}
          {{ cloud_humidity | float(0) | round(1) }}
        {% else %}
          {{ state_attr('climate.office_thermostat_1', 'current_humidity') }}
        {% endif %}
    - name: Office - Total power
      unique_id: 9a97bcb4-5d9d-40ce-b2ef-0f6eab474d4a
      unit_of_measurement: "W"
      device_class: power
      state: >-
        {{ expand('group.office_power_sensors') 
        | rejectattr('state', 'in', ['unavailable','unknown']) 
        | map(attribute='state') 
        | map('float') 
        | sum
        | float(0)
        | round(2)
        }}

#    - name: Office - Total energy
#      unique_id: 624bd673-b7df-4b0b-9d5b-517764d43d9c
#      unit_of_measurement: "kWh"
#      device_class: energy
#      state: >-
#        {{ 0
#        +  (states('sensor.office_ceiling_lights_energy') | float(0))
#        +  (states('sensor.office_windows_energy') | float(0))
#        +  (states('sensor.office_workstation_wall_outlet_energy') | float(0))
#        }}
