sensor:
  - name: Total power
    platform: group
    unique_id: cfc588f6-3143-42d6-968b-1e669e3c7ca4
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.balcony_total_power
      - sensor.bathroom_total_power
      - sensor.bedroom_total_power
      - sensor.corridor_total_power
      - sensor.guest_room_total_power
      - sensor.guest_bathroom_total_power
      - sensor.hall_total_power
      - sensor.kitchen_total_power
      - sensor.laundry_total_power
      - sensor.living_room_total_power
      - sensor.media_centre_total_power
      - sensor.office_total_power

  - name: Total energy
    platform: group
    unique_id: e6ea5908-d766-47d8-979c-c9b684f42752
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total #measurement
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.balcony_total_energy
      - sensor.bathroom_total_energy
      - sensor.bedroom_total_energy
      - sensor.corridor_total_energy
      - sensor.guest_room_total_energy
      - sensor.guest_bathroom_total_energy
      - sensor.hall_total_energy
      - sensor.kitchen_total_energy
      - sensor.laundry_total_energy
      - sensor.living_room_total_energy
      - sensor.media_centre_total_energy
      - sensor.office_total_energy
