decluttering_templates: !include_dir_merge_named  /config/lovelace/library/decluttering_templates/

title: System monitoring
views: #!include_dir_merge_list views/
  - !include views/overview.yaml
  - !include views/devices.yaml
  - !include views/sandbox.yaml
