automation:
- alias: Bedroom - Always on
  id: c7ffed8e-cb93-4435-8f08-69b6115897bd
  description: ''
  use_blueprint:
    path: EdwardTFN/always_on.yaml
    input:
      timeout: 60
      entities_list:
      - switch.bedroom_power_strip_1_echo
      - switch.bedroom_power_strip_1_usb

sensor:
  - name: Bedroom - Total power
    platform: group
    unique_id: d8e8383e-16eb-4324-a6b6-586699762b63
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.bedroom_ceiling_lights_power
      - sensor.bedroom_closet_lights_power
      - sensor.bedroom_closet_outlets_power
      - sensor.bedroom_outlets_carol_power
      - sensor.bedroom_outlets_edward_power
      - sensor.bedroom_tv_rack_power
