automation:
- alias: Bedroom - Apple TV - Turn on/off together with TV
  id: '1671816500266'
  description: ''
  use_blueprint:
    path: EdwardTFN/set_entities_based_on_other_entities.yaml
    input:
      input_entities:
      - switch.bedroom_power_strip_1_socket_4
      target_entities:
      - switch.bedroom_power_strip_1_socket_2
media_player:
  - name: Bedroom - TV Samsung - Universal
    platform: universal # https://www.home-assistant.io/integrations/universal/
    unique_id: 5974bb5b-cedd-406e-a382-afe424612da4
    device_class: tv
    icon: "{{ iif(is_state('switch.bedroom_power_strip_1_socket_4', 'on'), 'mdi:television', 'mdi:television-off') }}"
    children:
      - media_player.bedroom_tv_samsung_dlna
      - media_player.bedroom_tv_samsung_integration
    commands:
      turn_on:
        service: switch.turn_on
        data: {}
        target:
          entity_id: switch.bedroom_power_strip_1_socket_4
      turn_off:
        service: switch.turn_off
        data: {}
        target:
          entity_id: switch.bedroom_power_strip_1_socket_4
      volume_up:
        service: media_player.volume_set
        data:
          volume_level: "{{ min(1,(state_attr('media_player.bedroom_tv_samsung_integration', 'volume_level') | float(0)) + 0.01) }}"
        target:
          entity_id: media_player.bedroom_tv_samsung_integration
      volume_down:
        service: media_player.volume_set
        data:
          volume_level: "{{ max(0,(state_attr('media_player.bedroom_tv_samsung_integration', 'volume_level') | float(0)) - 0.01) }}"
        target:
          entity_id: media_player.bedroom_tv_samsung_integration
      volume_mute:
        service: media_player.volume_mute
        data:
          is_volume_muted: "{{ is_state_attr('media_player.bedroom_tv_samsung_dlna', 'is_volume_muted', false) | default(true) }}"
        target:
          entity_id: media_player.bedroom_tv_samsung_dlna
      volume_set:
        service: media_player.volume_set
        data:
          volume_level: "{{ volume_level }}"
        target:
          entity_id: media_player.bedroom_tv_samsung_integration
      #media_play:
        #service: media_player.media_play
        #data: {}
        #target:
          #entity_id: media_player.bedroom_tv_samsung_integration
      #media_pause:
        #service: media_player.media_pause
        #data: {}
        #target:
          #entity_id: media_player.bedroom_tv_samsung_integration
      #media_previous_track:
        #service: media_player.media_previous_track
        #data: {}
        #target:
          #entity_id: media_player.bedroom_tv_samsung_integration
      #media_next_track:
        #service: media_player.media_next_track
        #data: {}
        #target:
          #entity_id: media_player.bedroom_tv_samsung_integration
    attributes:
      state: switch.bedroom_power_strip_1_socket_4
      volume_level: media_player.bedroom_tv_samsung_dlna|volume_level
      is_volume_muted: media_player.bedroom_tv_samsung_dlna|is_volume_muted


rest_command:
  switchbot_scenes_bedroom_samsung_tv_ok:
    url: !secret switchbot_scenes_bedroom_samsung_tv_ok_execute_url
    method: post
    content_type: "application/json"
    headers:
      Authorization: !secret switchbot_api

#samsungtv: # https://www.home-assistant.io/integrations/samsungtv/
  #- name: Bedroom - Samsung Smart TV
    #unique_id: 9201a753-6f85-483f-844a-1311a654b19b
    #host: 192.168.12.32
    #turn_on_action:
      #- service: wake_on_lan.send_magic_packet
        #data:
          #mac: 38:01:95:69:05:36


#script:
  #tv_samsung_volume_up:
    #alias: TV Samsung - Volume up
    #sequence:
    #- service: media_player.volume_set
      #data:
        #volume_level: '{{ (state_attr(''media_player.tv_samsung'', ''volume_level'')
          #| float(0)) + 0.02 }}'
      #target:
        #entity_id: media_player.tv_samsung
    #mode: single
    #icon: mdi:volume-plus
  #tv_samsung_volume_down:
    #alias: TV Samsung - Volume down
    #sequence:
    #- service: media_player.volume_set
      #data:
        #volume_level: '{{ (state_attr(''media_player.tv_samsung'', ''volume_level'')
          #| float(0)) - 0.02 }}'
      #target:
        #entity_id: media_player.tv_samsung
    #mode: single
    #icon: mdi:volume-minus

switch:
  - platform: template
    switches:
      bedroom_tv_samsung_switchbot: # https://github.com/OpenWonderLabs/SwitchBotAPI
        friendly_name: Bedroom - TV Samsung - SwitchBot control
        value_template: "{{ is_state('media_player.bedroom_tv_samsung_integration', 'on') }}"
        turn_on:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_tv_deviceId
            command: "turnOn"
        turn_off:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_tv_deviceId
            command: "turnOff"
        icon_template: >-
          {% if is_state('media_player.bedroom_tv_samsung_integration', 'on') %}
            mdi:television
          {% else %}
            mdi:television-off
          {% endif %}

#wake_on_lan:
