#template:
#  - sensor:
#    - name: Bedroom - Total power
#      unique_id: 380d9ded-7be6-4cbc-b409-353baf8c9b96
#      unit_of_measurement: "W"
#      device_class: power
#      state: >-
#        {{ expand('group.bedroom_power_sensors') 
#        | rejectattr('state', 'in', ['unavailable','unknown']) 
#        | map(attribute='state') 
#        | map('float') 
#        | sum
#        | float(0)
#        | round(2)
#        }}

sensor:
  - name: Bedroom - Total power
    platform: group
    unique_id: d8e8383e-16eb-4324-a6b6-586699762b63
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.bedroom_ceiling_lights_power
      - sensor.bedroom_closet_lights_power
      - sensor.bedroom_closet_outlets_power
      - sensor.bedroom_outlets_carol_power
      - sensor.bedroom_outlets_edward_power
      - sensor.bedroom_tv_rack_power
