automation:
- alias: Balcony - Door - Announce to Alexa
  id: '1669284734009'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.balcony_door
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      target: Kitchen
      message: The balcony''s door is open.
  mode: single
