sensor:
  - name: Balcony - Total power
    platform: group
    unique_id: 68b06246-8522-4759-bf20-e3e8d5ea13b3
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities: 
      - sensor.balcony_lamp_light_power
      - sensor.balcony_lamp_sockets_power
      - sensor.balcony_string_lights_power

  - name: Balcony - Total energy
    platform: integration
    unique_id: 7f1885fd-0935-4d2d-91ce-27d7e1146ab0
    source: sensor.balcony_total_power
    round: 2
    unit_prefix: k
    unit_time: h
    method: trapezoidal
