automation:
- alias: Balcony - String lights - Door based
  id: '1644095579661'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.balcony_door
    from:
    - 'on'
    - 'off'
    to:
    - 'on'
    - 'off'
  - platform: state
    entity_id: sensor.civil_solar_day_status
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.balcony_door
      state: 'on'
    - condition: state
      entity_id: sensor.civil_solar_day_status
      state: night
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.balcony_string_lights
    else:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.balcony_string_lights
  mode: restart
- alias: Balcony - String lights - Sun based
  id: '1661722572465'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.civil_solar_day_status
  - platform: state
    entity_id:
    - sensor.electricity_price
    attribute: price_level_combined
  - platform: time
    at: 05:30:01
  - platform: time
    at: '23:30:01'
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '-3'
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: '-3'
  condition: []
  action:
  - if:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: '-3'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.electricity_price
        attribute: price_level_combined
        state: Normal
      - condition: state
        entity_id: sensor.electricity_price
        attribute: price_level_combined
        state: Cheap
      - condition: state
        entity_id: sensor.electricity_price
        attribute: price_level_combined
        state: Very cheap
    - condition: time
      after: 05:30:00
      before: '23:30:00'
    then:
    - if:
      - condition: state
        entity_id: light.balcony_string_lights
        state: 'off'
      then:
      - service: light.turn_on
        data:
          transition: 2
          brightness_pct: 15
        target:
          entity_id: light.balcony_string_lights
    else:
    - if:
      - condition: state
        entity_id: input_boolean.home_party_mode
        state: 'off'
      - condition: or
        conditions:
        - condition: not
          conditions:
          - type: is_open
            condition: device
            device_id: 8021128bf685776f421e7251ce5e5da5
            entity_id: binary_sensor.balcony_door
            domain: binary_sensor
      then:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.balcony_string_lights
  mode: restart