sensor:
  - name: Balcony - Total power
    platform: group
    unique_id: 68b06246-8522-4759-bf20-e3e8d5ea13b3
    unit_of_measurement: "W"
    device_class: power
    type: sum
    ignore_non_numeric: true
    entities:
      - sensor.balcony_lamp_light_power
      - sensor.balcony_lamp_sockets_power
      - sensor.balcony_string_lights_power
