substitutions:
  device_name: "guest-room-panel"
  friendly_name: Guest room - Panel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 3s
    files:
      - nspanel_esphome.yaml # Base package including TFT transfer
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
