substitutions:
  device_name: "hall-panel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel/nspanel_eu.tft"

packages:
  #device_base: !include packages/base_sonoff_nspanel.yaml
  #debug: !include packages/config_debug_esp32.yaml
  #local_package: !include packages/nspanel_esphome.yaml
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 1s

esp32:
  framework:
    type: esp-idf

#bluetooth_proxy:
