substitutions:
  device_name: "kitchen-windows-outlet"
  friendly_name: "Kitchen - Windows - Outlet"
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"

packages:
  device_base: !include packages/base_shelly_plus_1pm.yaml
#  ld2410_provision: !include packages/config_ld2410ble_mac_discovery.yaml
#  ld2410_presence: !include { file: packages/config_ld2410ble.yaml, vars: { mac_address: 'C5:69:CB:7F:A3:F4', ld2410_name: 'Kitchen - Windows - Outlet Presence ', ld2410_id: 'kitchen_table_presence_' } }

#esp32_ble_tracker:
#  scan_parameters:
#    interval: 160ms
#    window: 100ms
#    active: false

#bluetooth_proxy:
#  active: false

wifi:
  manual_ip:
    static_ip: !secret ip_kitchen-windows-outlet
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1
    dns2: !secret dns2