substitutions:
  device_name: living-room-proxy
  friendly_name: Living room - Proxy

#esphome:
  #name: living-room-proxy
  #friendly_name: Living room - Proxy

packages:
  #wifi: !include packages/config_wifi.yaml
  device_base: !include packages/base_az_delivery_esp32_d1_mini.yaml #_esp-idf.yaml
  # https://github.com/home-assistant/core/issues/90100#issuecomment-1483832015
  #hall_presence: !include { file: packages/config_ld2410ble.yaml, vars: { mac_address: 'D7:EB:A7:A5:49:A5', ld2410_name: 'Hall - Presence ', ld2410_id: 'hall_presence_' } }
  #kitchen_table_presence: !include { file: packages/config_ld2410ble.yaml, vars: { mac_address: 'C5:69:CB:7F:A3:F4', ld2410_name: 'Kitchen - Table - Presence ', ld2410_id: 'kitchen_table_presence_' } }
  #temp: !include { file: packages/config_ld2410ble.yaml, vars: { mac_address: '12:9A:88:63:19:A7', ld2410_name: 'Temp ', ld2410_id: 'temp_' } }
  #ld2410_provision: !include packages/config_ld2410ble_mac_discovery.yaml

#esp32_ble_tracker:
  #scan_parameters:
    #interval: 160ms
    #window: 100ms
    #active: false

#bluetooth_proxy:
  #active: false

api:
  id: api_server
  services:
    - service: test_alarm
      #variables:
      #  code: string
      then:
        - lambda: |-
            HomeassistantServiceResponse resp;
            resp.service = "alarm_control_panel.alarm_arm_away";
            HomeassistantServiceMap entity_id_kv;
            entity_id_kv.key = "entity_id";
            entity_id_kv.value = "alarm_control_panel.virtual_alarm_panel";
            resp.data.push_back(entity_id_kv);
            entity_id_kv.key = "code";
            entity_id_kv.value = "1122";
            resp.data.push_back(entity_id_kv);
            id(api_server).send_homeassistant_service_call(resp);
