substitutions:
  device_name: office-workstation-panel
  friendly_name: My panel #"Office - Workstation - Panel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel/nspanel_blank.tft"
  embedded_thermostat_disabled: "false"
  embedded_thermostat_heater_relay: "1"
  embedded_thermostat_min_heating_off_time: "300"
  embedded_thermostat_min_heating_run_time: "300"
  embedded_thermostat_min_idle_time: "30"


packages:
  #device_base: !include packages/base_sonoff_nspanel.yaml
  #debug: !include packages/config_debug_esp32.yaml
  local_package: !include packages/nspanel_esphome.yaml
  #remote_package:
  #  url: https://github.com/Blackymas/NSPanel_HA_Blueprint
  #  ref: dev
  #  files: [nspanel_esphome.yaml]
  #  refresh: 300s


climate:
  - platform: thermostat
    name: ${device_name} Thermostat
    sensor: temp_nspanel
    min_heating_off_time: ${embedded_thermostat_min_heating_off_time}s
    min_heating_run_time: ${embedded_thermostat_min_heating_run_time}s
    min_idle_time: ${embedded_thermostat_min_idle_time}s
    heat_action:
      - switch.turn_on: relay_${embedded_thermostat_heater_relay}
    idle_action:
      - switch.turn_off: relay_${embedded_thermostat_heater_relay}
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 21 °C
    internal: ${embedded_thermostat_disabled}

