substitutions:
  device_name: office-workstation-presence
  device_verbose_name: "Office - Workstation - Presence"

packages:
  #wifi: !include packages/config_wifi.yaml
  device_base: !include packages/base_az_delivery_esp32_d1_mini_esp-idf.yaml
  # https://github.com/home-assistant/core/issues/90100#issuecomment-1483832015
  #ld2410_1: !include { file: packages/config_ld2410ble.yaml, vars: { mac_address: 'DD:C7:6C:3F:F3:E3', ld2410_name: 'Office - Workstation ', ld2410_id: 'office_workstation' } }
  #ld2410_2: !include { file: packages/config_ld2410ble.yaml, vars: { mac_address: 'EE:7E:5B:A2:69:DE', ld2410_name: 'Office - Workstation 2', ld2410_id: 'office_workstation_2' } }
  #ld2410_provision: !include packages/config_ld2410ble_mac_discovery.yaml
  #ld2410_provision: github://dgrnbrg/appdaemon-configs/ld2410ble_mac_discovery.yaml@main
  #ld2410_2: !include { file ld2410ble.yaml, vars: { mac_address: 'XX:XX:E2:BB:27:XX', ld2410_name: "Kitchen ", ld2410_id: "kitchen" } }

#esp32_ble_tracker:
#  scan_parameters:
#    interval: 160ms
#    window: 100ms
#    active: false

#bluetooth_proxy:
#  active: false

#binary_sensor:
#  - platform: ble_presence
#    mac_address: DD:C7:6C:3F:F3:E3
#    name: "Office - Workstation - LD2410C - BLE Presence"
#    device_class: connectivity

#sensor:
#  - platform: ble_rssi
#    mac_address: DD:C7:6C:3F:F3:E3
#    name: "Office - Workstation - LD2410C - BLE RSSI"
#    device_class: signal_strength
#    state_class: measurement
#    icon: mdi:signal

ota:
  password: !secret ota_password
