esphome:
  name: wifi-smart-socket-ps-15
  friendly_name: WIFI Smart Socket PS-15

esp8266:
  board: esp01_1m

# Enable logging
logger:

packages:
  wifi: !include packages/config_wifi.yaml
  time: !include packages/config_sntp.yaml

captive_portal:

api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button"
    filters:
      - delayed_on_off: 50ms
    on_press:
      then:
        - switch.toggle: power_relay

    id: switchid
  - platform: status
    name: "Status"
  - platform: gpio
    pin: GPIO2
    name: "Sensor"

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: power_relay
    restore_mode: RESTORE_DEFAULT_ON

output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO13
      inverted: true

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "LED"
    output: state_led

button:
  - <<: !include packages/button_restart.yaml
  - <<: !include packages/button_restart_safe_mode.yaml
  - <<: !include packages/button_wifi_restart.yaml

sensor:
  - <<: !include packages/sensor_uptime.yaml
  - <<: !include packages/sensor_wifi.yaml
  - <<: !include packages/sensor_wifi_signal_percentage.yaml
  - <<: !include packages/sensor_esp_vcc_voltage.yaml
text_sensor:
  - <<: !include packages/text_sensor_version.yaml

